on:
  push:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt
      - name: Install Certificate
        run: |
          echo "${{ secrets.CERTIFICATE_BASE64 }}" | base64 --decode -o certificate.p12
          security create-keychain -p "temp_password" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "temp_password" build.keychain
          security import certificate.p12 -k build.keychain -P ${{ secrets.CERTIFICATE_PASSWORD }} -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "temp_password" build.keychain
      - run: pyinstaller SmartImageShrink_v0.6.spec
      - name: Sign Application
        run: |
          codesign --sign "${{ secrets.DEVELOPER_ID }}" --deep --options runtime --force --verbose dist/SmartImageShrink_v0.6.app
          codesign --verify --deep --strict --verbose=2 dist/SmartImageShrink_v0.6.app
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*
          compression-level: 9