on:
  push:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt
      - run: pyinstaller --noconsole --name="SmartImageShrink_v0.8" --icon="img/icon.png" --add-data="img:img" main.py
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*
          compression-level: 9